// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    ContactDetails: typeof import('./src/components/ContactDetails.vue')['default']
    FinalCard: typeof import('./src/components/FinalCard.vue')['default']
    PictureUpload: typeof import('./src/components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabWrapper: typeof import('./src/components/TabWrapper.vue')['default']
  }
}

export {}
